apiVersion: v1
kind: Service
metadata:
   name: hello-node-service
spec:
   selector:
     app: demoApp
   type: NodePort
   ports:
     - protocol: TCP
       port: 3001
       targetPort: 8888
       nodePort: 30000